### ISSUE TITLE
Roadmap V1.0

### ISSUE THREAD

**Issue by leonlan** [leonlan/VRPLIB#18]
The library currently supports reading and downloading instances from the CVRPLIB library. I'm going to work towards a V1 version of this library to make it support more general VRPLIB instances, particularly those from the [LKH-3 library](http://webhotel4.ruc.dk/~keld/research/LKH-3/). I think that the LKH-3 and CVRPLIB library are currently the best maintained VRP libraries with a consistent format. Moreover, LKH-3 has way more instances than CVRPLIB, which only has CVRP and VRPTW instances.

New features that I want to introduce:
- [x] Read LKH-3 VRPLIB formatted instances
- [x] Write VRPLIB formatted instances #14 
- [x] Extensively test VRPLIB reading

Some edge cases (mostly about how to support CVRPLIB):
- [x] Maybe drop support for downloading CVRPLIB instances? I think it's nice feature to have, but such a feature adds complexity to the library.
    - I'll keep the `download` feature for now because I think it's quite useful for running quick instances on Colab.
- [x] Maybe drop support for Solomon/GH instances that are not formatted by VRPLIB standards? I think we need this still because CVRPLIB relies on it.
    - We will not drop support for Solomon-formatted instances. Instead, `read_instance` will take the `style` argument which allows to parse different instance formatting styles (i.e., `vrplib` and `solomon`).

Issues
- [x] #40

**Comment by leonlan** [comment]
I have implemented most features that I wanted to for V1. The remaining things are mainly 1) testing and 2) documentation. This is something I need more time for, which I don't have the coming month. I'll continue working on this in January.

**Comment by leonlan** [comment]
I'll probably rename this package to `vrplib` as well, because that name fits the new features much better.

**Comment by leonlan** [comment]
Done now that V1 is released.
